### ISSUE TITLE
Insert On and Off?

### ISSUE THREAD

**Issue by arshcaria** [roidayan/KeyboardIndicator#6]
Currently we have `capslock `, `numlock`, `scrolllock` with `ON` and `OFF` modes. But pressing `insert` key only shows `Insert`, without `ON` and `OFF`.

Is is possible to add `ON` and `OFF` modes for `insert` key?

**Comment by roidayan** [comment]
hi,

as far as i remember when i checked this. Windows does not report if insert
is on or off. so its not possible.
its app dependent. example in one editor app you can be in insert mode and
in another editor app in replace mode. etc.

**Comment by arshcaria** [comment]
Thank you. I tried it on some programs and it's exactly like what you said.

Seems Windows only send the insert key event and let apps record their only insertion state.
